# -*- coding: utf-8 -*-
"""Análise Mercado Bitcoin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydck_km4CYHTbpyEmCGIk_uKEEIVfDLq

# Imports
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

"""# Leitura da Base de Dados"""

dados = pd.read_excel("Dados_Bitcoin.xlsx")

dados.head(10)

"""# Análise do Preço Histórico (2017 - 2022)


"""

dados.set_index("Date", inplace = True)

figure = px.line(dados, y = "Close")

figure.show()

"""# Análise de Preço Histórico, Média Móvel e Tendência"""

media_movel = dados["Close"].rolling(5).mean()
media_tendencia = dados["Close"].rolling(30).mean()

figure = go.Figure()

figure.add_trace(
    go.Scatter(
        x = dados.index,
        y = dados["Close"],
        mode =  "lines",
        name = "Fechamento",
        marker_color = "#FF760E",
        opacity = 0.7
  )
)

figure.add_trace(
    go.Scatter(
        x = dados.index,
        y = media_movel,
        mode =  "lines",
        name = "Média Móvel",
        marker_color = "#5A32DB",
        opacity = 0.7
  )
)

figure.add_trace(
    go.Scatter(
        x = dados.index,
        y = media_tendencia,
        mode =  "lines",
        name = "Tendência",
        marker_color = "#32DB3C"
  )
)

figure.update_layout(
    title = "Análise do Fechamento Bitcoin (2017 - 2022)",
    titlefont_size = 20,
    xaxis = dict(
        title = "Período Histórico",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    yaxis = dict(
        title = "Preço Fechamento ($)",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    legend = dict(
        bordercolor = "black",
        borderwidth = 0.5
    )
)

"""# Análise OLHC (Candlestick)"""

figure = go.Figure()

figure.add_trace(
    go.Candlestick(
        x = dados.index,
        open = dados["Open"],
        high = dados["High"],
        low = dados["Low"],
        close = dados["Close"],
      )
)

figure.update_layout(
    title = "Análise de Altas e Baixas do Bitcoin (2017 - 2022)",
    titlefont_size = 20
)

"""# Análise de Valor Máximo e Mínimo em cada Ano - (2017 - 2022)"""

min_valor = dados.reset_index()
max_valor = dados.reset_index()

min_valor["Date"] = pd.to_datetime(min_valor["Date"])
min_valor["Ano"] = min_valor["Date"].dt.year
min_valor.drop("Date", axis=1, inplace = True)
min_valor = min_valor.groupby("Ano").min().reset_index()

max_valor["Date"] = pd.to_datetime(max_valor["Date"])
max_valor["Ano"] = max_valor["Date"].dt.year
max_valor.drop("Date", axis=1, inplace = True)
max_valor = max_valor.groupby("Ano").max().reset_index()

figure = go.Figure()

figure.add_trace(
    go.Bar(
        x = max_valor["Ano"],
        y = max_valor["High"],
        name = "Valor Máximo"
    )
)

figure.add_trace(
    go.Bar(
        x = min_valor["Ano"],
        y = min_valor["High"],
        name = "Valor Mínimo"
    )
)

figure.update_layout(
    title = "Valor Máximo e Mínimo por Ano (2017 - 2022)",
    titlefont_size = 20,
    xaxis = dict(
        title = "Ano",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    yaxis = dict(
        title = "Valor ($)",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    legend = dict(
        bordercolor = "black",
        borderwidth = 0.5
    )
)

figure.show()

"""# Análise de Volume por Mês"""

vol_mes = dados.reset_index()

vol_mes["Date"] = pd.to_datetime(vol_mes["Date"])
vol_mes["Ano e Mes"] = vol_mes["Date"].dt.to_period("M")
vol_mes.drop("Date", axis=1, inplace = True)
vol_mes = vol_mes.groupby("Ano e Mes").sum().reset_index()

figure = go.Figure()

figure.add_trace(
    go.Bar(
        x = vol_mes["Ano e Mes"].astype(str),
        y = vol_mes["Volume"],
        name = "Volume por Mês ($)",
        marker=dict(
            color = vol_mes["Volume"],
            colorscale = "Viridis",
            showscale = True
        )
    )
)

figure.update_layout(
    title = "Volume por Mês (03/2017 - 02/2022)",
    titlefont_size = 20,
    xaxis = dict(
        title = "Ano-Mês",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    yaxis = dict(
        title = "Volume",
        titlefont_size = 14,
        tickfont_size = 11
    ),
    legend = dict(
        bordercolor = "black",
        borderwidth = 0.5
    )
)

figure.show()